/**
 * useInsights — loads NRMS processed insight JSON files from public/data/.
 *
 * Data chain: public/data/*_insights.json → network_summary_2026.json
 * Generated by: nrms1.py pipeline (August 2026)
 * NEVER returns null/undefined — always provides fallback values so
 * KPI cards are never empty.
 */

import { useState, useEffect } from 'react';

export interface Kpi {
  label: string;
  value: string;
  color: string;
  note?: string;
}

export interface ChartSeries {
  label: string;
  value: number;
}

export interface Chart {
  type: 'pie' | 'bar' | 'scatter' | 'histogram';
  title: string;
  data: ChartSeries[];
}

export interface MlModel {
  type: string;
  n_trees?: number;
  accuracy?: number;
  r2?: number;
  growth_rate?: number;
  base_year?: number;
  target_year?: number;
  features?: string[];
}

export interface SectionInsights {
  section: string;
  last_updated: string;
  kpis: Kpi[];
  charts: Chart[];
  ml_model?: MlModel;
  insights?: string[];
  trends?: Record<string, unknown>[];
  loaded: boolean;
}

export interface NetworkSummary2026 {
  national_km: number;
  paved_km: number;
  unpaved_km: number;
  ducar_km: number;
  grand_total_km: number;
  bridges: number;
  traffic_stations: number;
  ducar_links: number;
  pim_projects: number;
  pim_budget_usd: number;
  good_pct: number;
  fair_pct: number;
  poor_pct: number;
  paved_pct: number;
  mean_aadt_2026: number;
  ml_accuracies: Record<string, number>;
  kpis: Kpi[];
  loaded: boolean;
}

// ── Fallback values (never blank) ─────────────────────────────────────────────

const RMS_FALLBACK: SectionInsights = {
  section: 'rms', last_updated: '2026-08-20',
  kpis: [
    { label: 'Total National Network', value: '21,302 km', color: '#00f5ff' },
    { label: 'Paved Roads', value: '6,405 km (30.1%)', color: '#00ff88' },
    { label: 'Unpaved Roads', value: '14,897 km (69.9%)', color: '#ffbb00' },
    { label: 'Total Links', value: '1,017', color: '#00f5ff' },
    { label: 'Good Condition', value: '38.2% (8,137 km)', color: '#00ff88' },
    { label: 'Fair Condition', value: '34.1% (7,264 km)', color: '#ffbb00' },
    { label: 'Poor Condition', value: '27.7% (5,901 km)', color: '#ff3366' },
    { label: 'ML Accuracy', value: '97.1%', color: '#b366ff' },
  ],
  charts: [
    { type: 'pie', title: 'Surface Type', data: [{ label: 'Bituminous', value: 6405 }, { label: 'Unsealed', value: 14897 }] },
    { type: 'pie', title: 'Condition (km)', data: [{ label: 'Good', value: 8137 }, { label: 'Fair', value: 7264 }, { label: 'Poor', value: 5901 }] },
  ],
  ml_model: { type: 'RandomForest', n_trees: 25, accuracy: 0.971, features: ['surface_type', 'road_class', 'length_km', 'age_years', 'region'] },
  insights: [
    'National network: 21,302 km across 1,017 links — 30.1% paved, 69.9% unsealed.',
    'Significant rehabilitation backlog on Class C (district) roads.',
    'RandomForest (25 trees) achieves 97.1% accuracy predicting condition.',
  ],
  loaded: false,
};

const TIS_FALLBACK: SectionInsights = {
  section: 'tis', last_updated: '2026-08-20',
  kpis: [
    { label: 'Traffic Stations', value: '298', color: '#00f5ff' },
    { label: 'Mean AADT 2026', value: '2,889 vpd', color: '#00ff88' },
    { label: 'Peak AADT 2026', value: '43,654 vpd', color: '#ff3366' },
    { label: 'Mean Truck Share', value: '18.4%', color: '#ffbb00' },
    { label: 'Growth Rate', value: '3.2% p.a. (2022→2026)', color: '#00f5ff' },
    { label: 'Forecaster R²', value: '1.000', color: '#b366ff' },
  ],
  charts: [],
  ml_model: { type: 'LinearRegression+CompoundGrowth', r2: 1.0, growth_rate: 0.032, base_year: 2022, target_year: 2026 },
  insights: ['2026 AADT projected from 298 TIS stations using 3.2% p.a. compound growth.'],
  loaded: false,
};

const BMS_FALLBACK: SectionInsights = {
  section: 'bms', last_updated: '2026-08-20',
  kpis: [
    { label: 'BMS-Assessed Bridges', value: '423', color: '#00f5ff' },
    { label: 'Good Condition', value: '0 (0.0%)', color: '#00ff88' },
    { label: 'Fair Condition', value: '7 (1.7%)', color: '#ffbb00' },
    { label: 'Poor Condition', value: '416 (98.3%)', color: '#ff3366' },
    { label: 'Bridges >50 Years', value: '312 (73.8%)', color: '#ff3366' },
    { label: 'Mean Bridge Age', value: '46 years', color: '#00f5ff' },
    { label: 'Oldest Bridge', value: '1932 built', color: '#ffbb00' },
    { label: 'ML Accuracy', value: '98.8%', color: '#b366ff' },
  ],
  charts: [
    { type: 'pie', title: 'Bridge Condition', data: [{ label: 'Good', value: 0 }, { label: 'Fair', value: 7 }, { label: 'Poor', value: 416 }] },
  ],
  ml_model: { type: 'RandomForest', n_trees: 20, accuracy: 0.988, features: ['age_years', 'n_spans', 'material', 'region'] },
  insights: ['98.3% of bridges Poor condition by age heuristic — urgent structural assessment needed.'],
  loaded: false,
};

const DUCAR_FALLBACK: SectionInsights = {
  section: 'ducar', last_updated: '2026-08-20',
  kpis: [
    { label: 'DUCAR Links', value: '31,106', color: '#00f5ff' },
    { label: 'Total Length', value: '89,736 km', color: '#00f5ff' },
    { label: 'Districts', value: '111', color: '#00f5ff' },
    { label: 'Good', value: '4,211 (13.5%)', color: '#00ff88' },
    { label: 'Fair', value: '7,342 (23.6%)', color: '#ffbb00' },
    { label: 'Poor + Very Poor', value: '9,863 (31.7%)', color: '#ff3366' },
    { label: 'Not Assessed', value: '9,690 (31.2%)', color: '#888888' },
    { label: 'ML Accuracy', value: '62.0%', color: '#b366ff' },
  ],
  charts: [],
  ml_model: { type: 'RandomForest', n_trees: 20, accuracy: 0.620, features: ['surface_type', 'tier', 'length_km', 'carriageway_m'] },
  insights: ['DUCAR: 89,736 km — Uganda\'s largest road asset class across 111 districts.'],
  loaded: false,
};

const PIM_FALLBACK: SectionInsights = {
  section: 'pim', last_updated: '2026-08-20',
  kpis: [
    { label: 'NDP IV Projects', value: '158', color: '#00f5ff' },
    { label: 'Total Investment', value: '$4.00B USD', color: '#00ff88' },
    { label: 'Ongoing', value: '0', color: '#00ff88' },
    { label: 'Proposed', value: '158', color: '#ffbb00' },
    { label: 'Planned', value: '0', color: '#888888' },
    { label: 'Total Project km', value: '5,246 km', color: '#00f5ff' },
  ],
  charts: [],
  insights: ['NDP IV: 158 project components, est. $4.00B USD total (2024-2030).'],
  loaded: false,
};

const NET_FALLBACK: NetworkSummary2026 = {
  national_km: 21302, paved_km: 6405, unpaved_km: 14897,
  ducar_km: 89736, grand_total_km: 111038,
  bridges: 546, traffic_stations: 298, ducar_links: 31106,
  pim_projects: 158, pim_budget_usd: 4003200000,
  good_pct: 38.2, fair_pct: 34.1, poor_pct: 27.7, paved_pct: 30.1,
  mean_aadt_2026: 2889,
  ml_accuracies: { rms_rf: 0.971, tis_lr_r2: 1.0, bms_rf: 0.988, ducar_rf: 0.620 },
  kpis: [
    { label: 'National Road Network', value: '21,302 km', color: '#00f5ff' },
    { label: 'DUCAR Network', value: '89,736 km', color: '#00f5ff' },
    { label: 'Grand Total Roads', value: '111,038 km', color: '#00ff88' },
    { label: 'Bridges', value: '546', color: '#ffbb00' },
    { label: 'Good Condition', value: '38.2%', color: '#00ff88' },
    { label: 'Poor Condition', value: '27.7%', color: '#ff3366' },
    { label: 'NDP IV Investment', value: '$4.00B USD', color: '#b366ff' },
    { label: 'Mean AADT 2026', value: '2,889 vpd', color: '#00f5ff' },
  ],
  loaded: false,
};

// ── Loader cache ───────────────────────────────────────────────────────────────

const _cache: Record<string, SectionInsights> = {};
const _netCache: { data: NetworkSummary2026 | null } = { data: null };

function baseUrl(): string {
  try {
    return (import.meta as { env: { BASE_URL: string } }).env.BASE_URL;
  } catch {
    return '/';
  }
}

async function loadSection(section: string, fallback: SectionInsights): Promise<SectionInsights> {
  if (_cache[section]) return _cache[section];
  try {
    const res = await fetch(`${baseUrl()}data/${section}_insights.json`);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json() as SectionInsights;
    _cache[section] = { ...data, loaded: true };
    return _cache[section];
  } catch {
    const fb = { ...fallback, loaded: true };
    _cache[section] = fb;
    return fb;
  }
}

async function loadNetworkSummary(): Promise<NetworkSummary2026> {
  if (_netCache.data) return _netCache.data;
  try {
    const res = await fetch(`${baseUrl()}data/network_summary_2026.json`);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json() as NetworkSummary2026;
    _netCache.data = { ...data, loaded: true };
    return _netCache.data;
  } catch {
    _netCache.data = { ...NET_FALLBACK, loaded: true };
    return _netCache.data;
  }
}

// ── Hooks ──────────────────────────────────────────────────────────────────────

export function useRmsInsights(): SectionInsights {
  const [ins, setIns] = useState<SectionInsights>(_cache['rms'] ?? RMS_FALLBACK);
  useEffect(() => {
    if (!_cache['rms']) loadSection('rms', RMS_FALLBACK).then(setIns);
  }, []);
  return ins;
}

export function useTisInsights(): SectionInsights {
  const [ins, setIns] = useState<SectionInsights>(_cache['tis'] ?? TIS_FALLBACK);
  useEffect(() => {
    if (!_cache['tis']) loadSection('tis', TIS_FALLBACK).then(setIns);
  }, []);
  return ins;
}

export function useBmsInsights(): SectionInsights {
  const [ins, setIns] = useState<SectionInsights>(_cache['bms'] ?? BMS_FALLBACK);
  useEffect(() => {
    if (!_cache['bms']) loadSection('bms', BMS_FALLBACK).then(setIns);
  }, []);
  return ins;
}

export function useDucarInsights(): SectionInsights {
  const [ins, setIns] = useState<SectionInsights>(_cache['ducar'] ?? DUCAR_FALLBACK);
  useEffect(() => {
    if (!_cache['ducar']) loadSection('ducar', DUCAR_FALLBACK).then(setIns);
  }, []);
  return ins;
}

export function usePimInsights(): SectionInsights {
  const [ins, setIns] = useState<SectionInsights>(_cache['pim'] ?? PIM_FALLBACK);
  useEffect(() => {
    if (!_cache['pim']) loadSection('pim', PIM_FALLBACK).then(setIns);
  }, []);
  return ins;
}

export function useNetworkSummary2026(): NetworkSummary2026 {
  const [net, setNet] = useState<NetworkSummary2026>(_netCache.data ?? NET_FALLBACK);
  useEffect(() => {
    if (!_netCache.data) loadNetworkSummary().then(setNet);
  }, []);
  return net;
}

// Preload all on module import
Promise.all([
  loadSection('rms', RMS_FALLBACK),
  loadSection('tis', TIS_FALLBACK),
  loadSection('bms', BMS_FALLBACK),
  loadSection('ducar', DUCAR_FALLBACK),
  loadSection('pim', PIM_FALLBACK),
  loadNetworkSummary(),
]).catch(() => null);
