/**
 * NPMSSection — National Pavement Management infographics.
 * ALL figures come from data/nrms_seed.json, which is generated by SQL queries
 * against scripts/nrms_schema.sql (see Admin Tools → SQL Schema). Nothing is
 * hardcoded here; road IDs follow the FY25-26 network master rule A001_Link01.
 * Full-width layout — no outer max-width margins. No Budget Allocation tab.
 */
import { useState, useEffect, useMemo, useRef } from 'react';

// ─── SEED TYPES (all variables defined) ──────────────────────────────────────
interface RegionRef      { code: string; name: string; color: string }
interface RegionSummary  { region: string; total_km: number; paved_km: number; good_pct: number; fair_pct: number; poor_pct: number; critical_pct: number; avg_iri: number }
interface ConditionBand  { code: string; name: string; color: string; iri_max: number | null }
interface Treatment      { code: string; name: string; unit_cost_m_ugx: number }
interface MaintRow       { priority: number; road_id: string; section: string; length_km: number; condition: string; condition_color: string; treatment: string; unit_cost_m_ugx: number; total_cost_m_ugx: number; region: string }
interface MaintTotal     { treatment: string; sections: number; km: number; cost_bn_ugx: number }
interface IriBin         { label: string; color: string; pct: number }
interface ClassIri       { class_label: string; surveyed_km: number; very_good: number; good: number; fair: number; poor: number; critical: number; avg_iri: number }
interface Kpi            { label: string; value: string; note: string }
interface MapRoad        { road_no: string; name: string; coords: [number, number][]; condition: string; color: string }
interface Seed {
  fiscal_year: string;
  regions: RegionRef[];
  region_summary: RegionSummary[];
  condition_bands: ConditionBand[];
  treatments: Treatment[];
  maintenance_register: MaintRow[];
  maintenance_totals: MaintTotal[];
  iri_distribution: IriBin[];
  class_iri: ClassIri[];
  kpis: Record<string, Kpi>;
  map_roads: MapRoad[];
}

const SEED_URL = `${import.meta.env.BASE_URL}data/nrms_seed.json`;
const BASEMAP_URL = 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}';
const LABELS_URL  = 'https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}';
const MAP_CENTER: [number, number] = [1.373, 32.290];
const MAP_ZOOM = 7;

type Subtab = 'kpis' | 'iri' | 'heatmap' | 'maintenance';

// ─── STYLES (full-width: no maxWidth margins) ────────────────────────────────
const s = {
  wrap:     { padding: '20px', width: '100%' } as React.CSSProperties,
  subtabs:  { display: 'flex', gap: 4, marginBottom: 20, flexWrap: 'wrap' as const },
  stab:     { padding: '8px 18px', borderRadius: 8, fontSize: 12, fontWeight: 700, cursor: 'pointer', border: '1px solid rgba(0,245,255,0.2)', background: 'rgba(255,255,255,0.03)', color: 'rgba(148,163,184,0.7)', transition: 'all .2s' } as React.CSSProperties,
  stabOn:   { background: 'rgba(0,245,255,0.13)', color: '#00f5ff', border: '1px solid rgba(0,245,255,0.4)' } as React.CSSProperties,
  kpiRow:   { display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(150px,1fr))', gap: 12, marginBottom: 18 } as React.CSSProperties,
  kpi:      { background: 'linear-gradient(145deg,rgba(0,245,255,0.07),rgba(2,5,8,0.8))', border: '1px solid rgba(0,245,255,0.16)', borderLeft: '3px solid #00f5ff', borderRadius: 12, padding: '14px 16px' } as React.CSSProperties,
  card:     { background: 'linear-gradient(135deg,rgba(0,245,255,0.05),rgba(2,5,8,0.6))', border: '1px solid rgba(0,245,255,0.14)', borderRadius: 12, padding: 16, marginBottom: 16 } as React.CSSProperties,
  lbl:      { color: 'rgba(148,163,184,0.65)', fontSize: 10, textTransform: 'uppercase' as const, letterSpacing: '.08em', fontWeight: 700 },
  val:      { color: '#00f5ff', fontSize: 22, fontWeight: 800, margin: '5px 0 2px', textShadow: '0 0 16px currentColor' } as React.CSSProperties,
  sub:      { color: 'rgba(100,116,139,0.7)', fontSize: 11 } as React.CSSProperties,
  h3:       { color: '#00f5ff', fontSize: 13, fontWeight: 800, marginBottom: 12, letterSpacing: '.04em' } as React.CSSProperties,
  table:    { width: '100%', borderCollapse: 'collapse' as const, fontSize: 12.5 } as React.CSSProperties,
  th:       { background: 'rgba(2,5,8,0.8)', color: '#00f5ff', padding: '9px 11px', textAlign: 'left' as const, fontSize: 10, textTransform: 'uppercase' as const, letterSpacing: '.06em', borderBottom: '1px solid rgba(0,245,255,0.15)' } as React.CSSProperties,
  td:       { padding: '9px 11px', borderBottom: '1px solid rgba(255,255,255,0.04)', color: '#b7c2d2', verticalAlign: 'middle' as const } as React.CSSProperties,
  badge:    { display: 'inline-block', padding: '2px 8px', borderRadius: 5, fontSize: 11, fontWeight: 700 } as React.CSSProperties,
  mapBox:   { height: 380, borderRadius: 10, border: '1px solid rgba(0,245,255,0.15)' } as React.CSSProperties,
};

// ─── COMPONENT ───────────────────────────────────────────────────────────────
export default function NPMSSection() {
  const [seed, setSeed] = useState<Seed | null>(null);
  const [seedError, setSeedError] = useState<string | null>(null);
  const [tab, setTab] = useState<Subtab>('kpis');
  const [treatFilter, setTreatFilter] = useState<string>('all');
  const iriRef  = useRef<HTMLCanvasElement>(null);
  const mapRef1 = useRef<HTMLDivElement>(null);
  const mapRef3 = useRef<HTMLDivElement>(null);
  const mapInst1 = useRef<unknown>(null);
  const mapInst3 = useRef<unknown>(null);

  // Load the SQL-generated seed — the only data source.
  useEffect(() => {
    let live = true;
    fetch(SEED_URL)
      .then(r => { if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.json(); })
      .then((j: Seed) => { if (live) setSeed(j); })
      .catch(e => { if (live) setSeedError(String(e)); });
    return () => { live = false; };
  }, []);

  const bandColor = useMemo(() => {
    const m: Record<string, string> = {};
    seed?.condition_bands.forEach(b => { m[b.name] = b.color; });
    return m;
  }, [seed]);

  const condBadge = (c: string) => {
    const col = bandColor[c] ?? 'rgba(148,163,184,0.7)';
    return <span style={{ ...s.badge, background: `${col}20`, color: col }}>{c}</span>;
  };

  // IRI histogram (Chart.js) — bins from SQL
  useEffect(() => {
    if (!seed || tab !== 'iri' || !iriRef.current) return;
    const ChartCtor = (window as any).Chart;
    if (!ChartCtor) return;
    const existing = (window as any).__iriChart;
    if (existing) existing.destroy();
    const ch = new ChartCtor(iriRef.current.getContext('2d'), {
      type: 'bar',
      data: {
        labels: seed.iri_distribution.map(b => b.label),
        datasets: [{ label: '% of Network', data: seed.iri_distribution.map(b => b.pct), backgroundColor: seed.iri_distribution.map(b => b.color) }],
      },
      options: {
        indexAxis: 'y', responsive: true, maintainAspectRatio: false,
        plugins: { legend: { display: false } },
        scales: {
          x: { ticks: { color: 'rgba(148,163,184,0.7)', callback: (v: unknown) => `${v}%` }, grid: { color: 'rgba(255,255,255,0.05)' } },
          y: { ticks: { color: 'rgba(174,185,201,0.9)', font: { size: 11 } } },
        },
      },
    });
    (window as any).__iriChart = ch;
  }, [seed, tab]);

  // Leaflet maps — road corridors from SQL geometry
  const buildMap = (el: HTMLDivElement | null, inst: React.MutableRefObject<unknown>, weight: number) => {
    const L = (window as any).L;
    if (!seed || !L || !el || inst.current) return;
    const m = L.map(el).setView(MAP_CENTER, MAP_ZOOM);
    L.tileLayer(BASEMAP_URL).addTo(m);
    L.tileLayer(LABELS_URL, { opacity: .7 }).addTo(m);
    seed.map_roads.forEach(r => {
      L.polyline(r.coords, { color: r.color, weight, opacity: .85 })
        .bindPopup(`<div style="background:#0a111c;padding:8px;color:#c7d2e0;min-width:150px"><b style="color:#00f5ff">${r.road_no}</b><br>${r.name}<br>Condition: <b style="color:${r.color}">${r.condition}</b></div>`)

        {/* ── Definition Card ── */}
        <div style={{background:'rgba(245,158,11,0.04)',border:'1px solid rgba(245,158,11,0.14)',borderRadius:16,padding:'20px 24px',marginBottom:24,display:'flex',alignItems:'flex-start',gap:16}}>
          <div style={{fontSize:36,lineHeight:1,flexShrink:0}}>🛣️</div>
          <div style={{flex:1}}>
            <div style={{display:'flex',alignItems:'center',gap:8,flexWrap:'wrap',marginBottom:4}}>
              <span style={{fontSize:18,fontWeight:800,color:'rgba(245,158,11,1)',letterSpacing:-0.5}}>NPMS Section Analytics</span>
              <span style={{fontSize:11,color:'#94a3b8',fontWeight:500}}>National PMS · Section Performance · IRI · PCI · Budget</span>
            </div>
            <p style={{fontSize:12,color:'#94a3b8',margin:'0 0 10px',lineHeight:1.6}}>National Pavement Management System section analytics — profiling pavement performance across Uganda road sections with IRI roughness trends, PCI condition distributions, HDM-4 treatment recommendations, and URF budget planning tools.</p>
            <div style={{display:'flex',gap:6,flexWrap:'wrap'}}>
              {["National PMS","Section Profile","IRI Analysis","PCI Distribution","HDM-4 Treatments","URF Budget"].map(b=>(
                <span key={b} style={{background:'rgba(245,158,11,0.12)',color:'rgba(245,158,11,0.9)',fontSize:9,fontWeight:700,borderRadius:20,padding:'2px 8px',textTransform:'uppercase' as const,letterSpacing:0.5}}>{b}</span>
              ))}
            </div>
          </div>
        </div>
        .addTo(m);
    });
    inst.current = m;
  };
  useEffect(() => { if (tab === 'kpis') buildMap(mapRef1.current, mapInst1, 4); }, [seed, tab]);
  useEffect(() => { if (tab === 'heatmap') buildMap(mapRef3.current, mapInst3, 5); }, [seed, tab]);

  const register = seed?.maintenance_register ?? [];
  const filteredMaint = useMemo(
    () => (treatFilter === 'all' ? register : register.filter(r => r.treatment === treatFilter)),
    [register, treatFilter],
  );
  const filteredCostBn = filteredMaint.reduce((a, r) => a + r.total_cost_m_ugx, 0) / 1000;

  const totalsByTreatment = useMemo(() => {
    const m: Record<string, MaintTotal> = {};
    seed?.maintenance_totals.forEach(t => { m[t.treatment] = t; });
    return m;
  }, [seed]);
  const totalNeedBn = (seed?.maintenance_totals ?? []).reduce((a, t) => a + t.cost_bn_ugx, 0);

  const kpi = (key: string): Kpi => seed?.kpis[key] ?? { label: key, value: '—', note: '' };

  const ST = (id: Subtab) => ({ ...s.stab, ...(tab === id ? s.stabOn : {}) });

  if (seedError) {
    return <div style={{ ...s.wrap, color: '#ff2d78', fontSize: 13 }}>Failed to load SQL seed data ({seedError}). Check data/nrms_seed.json.</div>;
  }
  if (!seed) {
    return <div style={{ ...s.wrap, color: 'rgba(148,163,184,0.7)', fontSize: 13 }}>Loading pavement data from SQL seed…</div>;
  }

  return (
    <div style={s.wrap}>
      {/* Subtabs — Budget Allocation removed (duplicated the Maintenance register) */}
      <div style={s.subtabs}>
        <button style={ST('kpis')}        onClick={() => setTab('kpis')}> KPIs by Region</button>
        <button style={ST('iri')}         onClick={() => setTab('iri')}> IRI Distribution</button>
        <button style={ST('heatmap')}     onClick={() => setTab('heatmap')}> Condition Map</button>
        <button style={ST('maintenance')} onClick={() => setTab('maintenance')}> Maintenance Needs</button>
      </div>

      {/* KPIs */}
      {tab === 'kpis' && <>
        <div style={s.kpiRow}>
          {(['surveyed_km', 'avg_iri', 'good_pct', 'need_treatment'] as const).map((k, i) => {
            const accent = [seed.regions[0]?.color ?? '#00f5ff', '#00ff88', '#ff6b35', '#ff2d78'][i];
            const item = kpi(k);
            return (
              <div key={k} style={{ ...s.kpi, borderLeftColor: accent }}>
                <div style={s.lbl}>{item.label}</div>
                <div style={{ ...s.val, color: accent }}>{item.value}</div>
                <div style={s.sub}>{item.note}</div>
              </div>
            );
          })}
        </div>
        <div style={s.card}>
          <div style={s.h3}>Region Summary — {seed.regions.length} Maintenance Regions · {seed.fiscal_year}</div>
          <table style={s.table}><thead><tr>
            {['Region', 'Total (km)', 'Paved (km)', 'Good %', 'Fair %', 'Poor %', 'Critical %', 'Avg IRI'].map(h => <th key={h} style={s.th}>{h}</th>)}
          </tr></thead><tbody>
            {seed.region_summary.map(r => {
              const accent = seed.regions.find(x => x.name === r.region)?.color ?? '#00f5ff';
              return (
                <tr key={r.region}>
                  <td style={s.td}><b style={{ color: accent }}>{r.region}</b></td>
                  <td style={s.td}>{r.total_km.toLocaleString()}</td>
                  <td style={s.td}>{r.paved_km.toLocaleString()}</td>
                  <td style={s.td}><span style={{ color: bandColor['Good'] }}>{r.good_pct}%</span></td>
                  <td style={s.td}><span style={{ color: bandColor['Fair'] }}>{r.fair_pct}%</span></td>
                  <td style={s.td}><span style={{ color: bandColor['Poor'] }}>{r.poor_pct}%</span></td>
                  <td style={s.td}><span style={{ color: bandColor['Critical'] }}>{r.critical_pct}%</span></td>
                  <td style={s.td}><b style={{ color: '#00f5ff' }}>{r.avg_iri}</b></td>
                </tr>
              );
            })}
          </tbody></table>
        </div>
        <div style={s.card}>
          <div style={s.h3}>Condition Map — Road Network by Region</div>
          <div ref={mapRef1} style={s.mapBox}></div>
          <div style={{ display: 'flex', gap: 16, marginTop: 10, fontSize: 12 }}>
            {seed.condition_bands.map(b => <span key={b.code} style={{ color: b.color }}>■ {b.name}</span>)}
          </div>
        </div>
      </>}

      {/* IRI Distribution */}
      {tab === 'iri' && <>
        <div style={s.kpiRow}>
          {(['avg_iri', 'target_iri', 'surveyed_km'] as const).map((k, i) => {
            const accent = ['#00f5ff', '#00ff88', '#ff6b35'][i];
            const item = kpi(k);
            return (
              <div key={k} style={{ ...s.kpi, borderLeftColor: accent }}>
                <div style={s.lbl}>{item.label}</div>
                <div style={{ ...s.val, color: accent }}>{item.value}</div>
                <div style={s.sub}>{item.note}</div>
              </div>
            );
          })}
        </div>
        <div style={s.card}>
          <div style={s.h3}>IRI Distribution — National Road Network</div>
          <div style={{ height: 320 }}><canvas ref={iriRef}></canvas></div>
          <div style={{ marginTop: 12, fontSize: 12, color: 'rgba(100,116,139,0.8)' }}>
            IRI = International Roughness Index (m/km) · bands per Road Condition Assessment Manual
          </div>
        </div>
        <div style={s.card}>
          <div style={s.h3}>IRI by Road Class</div>
          <table style={s.table}><thead><tr>
            {['Road Class', 'Length Surveyed', 'Very Good (0–2)', 'Good (2–4)', 'Fair (4–6)', 'Poor (6–8)', 'Critical (8+)', 'Avg IRI'].map(h => <th key={h} style={s.th}>{h}</th>)}
          </tr></thead><tbody>
            {seed.class_iri.map(c => (
              <tr key={c.class_label}>
                <td style={s.td}>{c.class_label}</td>
                <td style={s.td}>{c.surveyed_km.toLocaleString()} km</td>
                <td style={s.td}>{c.very_good}%</td>
                <td style={s.td}>{c.good}%</td>
                <td style={s.td}>{c.fair}%</td>
                <td style={s.td}>{c.poor}%</td>
                <td style={s.td}>{c.critical}%</td>
                <td style={s.td}><b style={{ color: c.avg_iri <= 4 ? '#00f5ff' : c.avg_iri <= 6 ? '#ff6b35' : '#ff2d78' }}>{c.avg_iri}</b></td>
              </tr>
            ))}
          </tbody></table>
        </div>
      </>}

      {/* Condition heatmap */}
      {tab === 'heatmap' && (
        <div style={s.card}>
          <div style={s.h3}>Road Condition Heatmap — Uganda National Network</div>
          <div style={{ display: 'flex', gap: 8, marginBottom: 12, flexWrap: 'wrap' }}>
            {seed.condition_bands.map(b => (
              <span key={b.code} style={{ padding: '4px 12px', borderRadius: 5, background: `${b.color}20`, color: b.color, fontSize: 12, fontWeight: 700, border: `1px solid ${b.color}44` }}>■ {b.name}</span>
            ))}
          </div>
          <div ref={mapRef3} style={s.mapBox}></div>
          <div style={{ marginTop: 8, fontSize: 11, color: 'rgba(100,116,139,0.8)' }}>Click any road corridor for condition details</div>
        </div>
      )}

      {/* Maintenance needs */}
      {tab === 'maintenance' && <>
        <div style={s.kpiRow}>
          <div style={s.kpi}>
            <div style={s.lbl}>Total Need {seed.fiscal_year}</div>
            <div style={s.val}>UGX {Math.round(totalNeedBn)}B</div>
            <div style={s.sub}>all treatment types</div>
          </div>
          {seed.maintenance_totals.filter(t => t.treatment !== 'Routine Maintenance').map(t => {
            const trigger = seed.treatments.find(x => x.name === t.treatment);
            const accent = t.treatment === 'Reconstruction' ? bandColor['Critical']
              : t.treatment === 'Rehabilitation' ? bandColor['Poor']
              : bandColor['Fair'];
            return (
              <div key={t.treatment} style={{ ...s.kpi, borderLeftColor: accent }}>
                <div style={s.lbl}>{t.treatment}</div>
                <div style={{ ...s.val, color: accent }}>UGX {Math.round(t.cost_bn_ugx)}B</div>
                <div style={s.sub}>{t.sections} sections · {t.km} km{trigger ? ` · ${trigger.unit_cost_m_ugx}M/km` : ''}</div>
              </div>
            );
          })}
        </div>
        <div style={{ display: 'flex', gap: 8, marginBottom: 14, flexWrap: 'wrap' }}>
          {['all', ...seed.treatments.map(t => t.name)].map(t => (
            <button key={t} onClick={() => setTreatFilter(t)} style={{ ...s.stab, ...(treatFilter === t ? s.stabOn : {}) }}>
              {t === 'all' ? 'All' : t}
            </button>
          ))}
        </div>
        <div style={s.card}>
          <div style={s.h3}>Maintenance Needs Register — {filteredMaint.length} sections | Total: UGX {Math.round(filteredCostBn)}B</div>
          <table style={s.table}><thead><tr>
            {['Road ID', 'Section', 'Region', 'Length (km)', 'Condition', 'Treatment', 'Unit Cost (M/km)', 'Total Cost (M)', 'Priority'].map(h => <th key={h} style={s.th}>{h}</th>)}
          </tr></thead><tbody>
            {filteredMaint.map(r => (
              <tr key={r.road_id}>
                <td style={s.td}><b style={{ color: '#00f5ff' }}>{r.road_id}</b></td>
                <td style={s.td}>{r.section}</td>
                <td style={s.td}><span style={{ color: seed.regions.find(x => x.name === r.region)?.color ?? '#b7c2d2', fontSize: 11.5 }}>{r.region}</span></td>
                <td style={s.td}>{r.length_km}</td>
                <td style={s.td}>{condBadge(r.condition)}</td>
                <td style={s.td}><span style={{ color: '#e0e6ee', fontSize: 12 }}>{r.treatment}</span></td>
                <td style={s.td}>UGX {r.unit_cost_m_ugx}M</td>
                <td style={s.td}><b style={{ color: '#ffd23f' }}>UGX {r.total_cost_m_ugx.toLocaleString()}M</b></td>
                <td style={s.td}><span style={{ color: r.priority > 9 ? '#ff2d78' : r.priority > 7 ? '#ff6b35' : '#00ff88', fontWeight: 700 }}>{r.priority.toFixed(1)}</span></td>
              </tr>
            ))}
          </tbody></table>
        </div>
      </>}
    </div>
  );
}
